import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      suppressHydrationWarning
    >
      <body suppressHydrationWarning className="flex flex-col ">
        <header className="py-4">
          <nav>
            <ul className="flex justify-center gap-x-3">
              <li>
                <Link href={"/register"} className="underline">
                  Register
                </Link>
              </li>
              <li>
                <Link href={"/protected"} className="underline">
                  Protected
                </Link>
              </li>
              <li>
                <Link href={"/"} className="underline">
                  Home
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        <main className="grid place-items-center">{children}</main>
      </body>
    </html>
  );
}
